Ok, now it's time to test the doctest in Python.

>>> 1 + 2 + 3

6

>>> 4 * 5

20

First test I wrote and they are bad. Why?  Stupid mistake on my part, I left a empty line between the promt and its answer. In other words.

>>> print("pato")

pato

Makes the interpreter think that the expected output is nothing. Meanwhile

>>> print("pato") 
pato

Work as expected.

Example of a multiline doctest:

>>> def duplicator(num):
...	return num * 2
>>> duplicator(4)
8

Exception handling in doctest, example.
>>> def snafu():
...    yield 'a'
...    return None
SyntaxError: 'return' with argument inside generator (<doctest doctestexample.txt[6], line 3)
